# Final thought

In this brief guide, we have covered a great deal of ground. The concepts we have discussed are the very core ones of the daily practice of programming. Every time you start to program you'll use reflection, sequences, iteration and re-doing in the problem solving and design phase. When you come to put code down you'll implement it with loops and conditionals,  variables and code re-use. 

These concepts underpin every programming language. When you move on to build programs in other languages you'll use all of them. The implementation of loops, conditionals, blocks and variables varies from language to language, but underneath they're all the sames. For you, all that remains is the challenge of understanding the specific syntax of the new language.

As I wrote at the beginning the process of making a program is slow, so your first scripts in the new language may not be the most amazing. They'll improve with practice. You don't need to be a genius to program computers, you just need patience with yourself and a little determination to get there.

Good Luck!

